name: LifeOps Notifications

on:
  workflow_dispatch:

  schedule:
    - cron: "30 1 * * *"   # 7:00 AM IST
    - cron: "30 14 * * *"  # 8:00 PM IST

jobs:

  # morning:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"

  #     - run: pip install -r requirements.txt

  #     - run: python -m scripts.send_morning
  #       env:
  #         BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  #         CHAT_ID_RUCHIR: ${{ secrets.CHAT_ID_RUCHIR }}

  evening:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python -m scripts.send_evening_meal
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID_SAKSHI: ${{ secrets.CHAT_ID_SAKSHI }}