name: LifeOps Notifications

on:
  workflow_dispatch:

  schedule:
    # 7:00 AM IST
    - cron: "30 1 * * *"

    # 8:00 PM IST
    - cron: "30 14 * * *"

jobs:

  morning:
    - run: python -m scripts.send_morning

  evening::
    - run: python -m scripts.send_evening_meal